### ISSUE TITLE
Firefox only - https (not http) hangs at splash screen

### ISSUE THREAD

**Issue by xRadio-us** [ltGuillaume/MusicFolderPlayer#13] opened 2019-02-19 23:30 UTC
I usually develop using Google Chrome.

My [**httpS** Dark Theme Version](https://xradio.us/start/dap/) works fine using Windows versions of Chrome and SeaMonkey but HANGS at the splash screen in the latest Windows Firefox.

The [**http** Dark Theme Version](http://xradio.us/start/dap/) works okay in Firefox.

**Comment by ltGuillaume** [comment] 2019-02-20 09:11
Unless you're using Waterfox, which is still at Firefox v56.x, this Firefox bug should be fixed (see https://stackoverflow.com/questions/44200990/html5-audio-player-in-firefox-is-not-working and https://bugzilla.mozilla.org/show_bug.cgi?id=1377278)

I just tried your HTTPS Dark Theme version on a clean portable Firefox 65 instance. Worked as intended.

**Closed** 2019-02-20 09:12 UTC
